In [73]:
import pandas as pd

df = pd.read_csv("../data/interim/cleaned.csv")

display(df.head())
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate,has_company
0,0,6,2015,July,27,1,0,2,1,0.0,...,No Deposit,6.0,0,Transient,0.0,0,0,Check-Out,2015-07-03,0
1,1,88,2015,July,27,1,0,4,2,0.0,...,No Deposit,9.0,0,Transient,76.5,0,1,Canceled,2015-07-01,0
2,1,65,2015,July,27,1,0,4,1,0.0,...,No Deposit,9.0,0,Transient,68.0,0,1,Canceled,2015-04-30,0
3,1,92,2015,July,27,1,2,4,2,0.0,...,No Deposit,9.0,0,Transient,76.5,0,2,Canceled,2015-06-23,0
4,1,100,2015,July,27,2,0,2,2,0.0,...,No Deposit,9.0,0,Transient,76.5,0,1,Canceled,2015-04-02,0

Shape: (53040, 31)
Columns: ['IsCanceled', 'LeadTime', 'ArrivalDateYear', 'ArrivalDateMonth', 'ArrivalDateWeekNumber', 'ArrivalDateDayOfMonth', 'StaysInWeekendNights', 'StaysInWeekNights', 'Adults', 'Children', 'Babies', 'Meal', 'Country', 'MarketSegment', 'DistributionChannel', 'IsRepeatedGuest', 'PreviousCancellations', 'PreviousBookingsNotCanceled', 'ReservedRoomType', 'AssignedRoomType', 'BookingChanges', 'DepositType', 'Agent', 'DaysInWaitingList', 'CustomerType', 'ADR', 'RequiredCarParkingSpaces', 'TotalOfSpecialRequests', 'ReservationStatus', 'ReservationStatusDate', 'has_company']

In [74]:
Y = df["IsCanceled"]

X = df.drop(columns=["IsCanceled"])

In [75]:
# Removed the cols  (ReservationStatus, ReservationStatusDate) because the model could learn to look at these cols 
X = X.drop(
    columns=["ReservationStatus", "ReservationStatusDate"],
    errors="ignore"
)
display(X.head())

,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,...,AssignedRoomType,BookingChanges,DepositType,Agent,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,has_company
0,6,2015,July,27,1,0,2,1,0.0,0,...,A,0,No Deposit,6.0,0,Transient,0.0,0,0,0
1,88,2015,July,27,1,0,4,2,0.0,0,...,A,0,No Deposit,9.0,0,Transient,76.5,0,1,0
2,65,2015,July,27,1,0,4,1,0.0,0,...,A,0,No Deposit,9.0,0,Transient,68.0,0,1,0
3,92,2015,July,27,1,2,4,2,0.0,0,...,A,0,No Deposit,9.0,0,Transient,76.5,0,2,0
4,100,2015,July,27,2,0,2,2,0.0,0,...,A,0,No Deposit,9.0,0,Transient,76.5,0,1,0

In [76]:
print("X shape:", X.shape)
print("y shape:", Y.shape)

print("\nTarget distribution:")
print(Y.value_counts())

print("\nFeature columns:")
print(X.columns.tolist())

X shape: (53040, 28)
y shape: (53040,)

Target distribution:
IsCanceled
0    37019
1    16021
Name: count, dtype: int64

Feature columns:
['LeadTime', 'ArrivalDateYear', 'ArrivalDateMonth', 'ArrivalDateWeekNumber', 'ArrivalDateDayOfMonth', 'StaysInWeekendNights', 'StaysInWeekNights', 'Adults', 'Children', 'Babies', 'Meal', 'Country', 'MarketSegment', 'DistributionChannel', 'IsRepeatedGuest', 'PreviousCancellations', 'PreviousBookingsNotCanceled', 'ReservedRoomType', 'AssignedRoomType', 'BookingChanges', 'DepositType', 'Agent', 'DaysInWaitingList', 'CustomerType', 'ADR', 'RequiredCarParkingSpaces', 'TotalOfSpecialRequests', 'has_company']

In [77]:


numeric_columns = X.select_dtypes(include=["number"]).columns.tolist()
categorical_columns = X.select_dtypes(exclude=["number"]).columns.tolist()

print("Number of numerical columns:", len(numeric_columns))
print(numeric_columns)

print("\nNumber of categorical columns:", len(categorical_columns))
print(categorical_columns)

Number of numerical columns: 19
['LeadTime', 'ArrivalDateYear', 'ArrivalDateWeekNumber', 'ArrivalDateDayOfMonth', 'StaysInWeekendNights', 'StaysInWeekNights', 'Adults', 'Children', 'Babies', 'IsRepeatedGuest', 'PreviousCancellations', 'PreviousBookingsNotCanceled', 'BookingChanges', 'Agent', 'DaysInWaitingList', 'ADR', 'RequiredCarParkingSpaces', 'TotalOfSpecialRequests', 'has_company']

Number of categorical columns: 9
['ArrivalDateMonth', 'Meal', 'Country', 'MarketSegment', 'DistributionChannel', 'ReservedRoomType', 'AssignedRoomType', 'DepositType', 'CustomerType']

In [78]:

for col in categorical_columns:
    print(f"\n{col}:")
    print("Number of unique values:", X[col].nunique())
    print(X[col].value_counts().head(10))

ArrivalDateMonth:
Number of unique values: 12
ArrivalDateMonth
August       6561
July         5714
May          5389
April        5062
June         4986
March        4811
September    4217
October      4157
February     3559
December     2983
Name: count, dtype: int64

Meal:
Number of unique values: 4
Meal
BB    40981
SC     9274
HB     2774
FB       11
Name: count, dtype: int64

Country:
Number of unique values: 166
Country
PRT    12931
FRA     7394
GBR     4513
DEU     4465
ESP     3775
ITA     2640
BEL     1690
BRA     1583
NLD     1429
USA     1411
Name: count, dtype: int64

MarketSegment:
Number of unique values: 8
MarketSegment
Online TA        34828
Offline TA/TO     7194
Direct            5483
Groups            2615
Corporate         2203
Complementary      493
Aviation           222
Undefined            2
Name: count, dtype: int64

DistributionChannel:
Number of unique values: 5
DistributionChannel
TA/TO        44298
Direct        5989
Corporate     2571
GDS            178
Undefined        4
Name: count, dtype: int64

ReservedRoomType:
Number of unique values: 7
ReservedRoomType
A    37650
D    10716
F     1749
E     1450
B      988
G      474
C       13
Name: count, dtype: int64

AssignedRoomType:
Number of unique values: 8
AssignedRoomType
A    33273
D    13164
E     2037
F     1959
B     1643
G      685
C      153
K      126
Name: count, dtype: int64

DepositType:
Number of unique values: 3
DepositType
No Deposit    52181
Non Refund      844
Refundable       15
Name: count, dtype: int64

CustomerType:
Number of unique values: 4
CustomerType
Transient          44318
Transient-Party     6994
Contract            1460
Group                268
Name: count, dtype: int64

In [79]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (42432, 28)
X_test shape: (10608, 28)
y_train shape: (42432,)
y_test shape: (10608,)

In [80]:

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

X_train_cat = encoder.fit_transform(
    X_train[categorical_columns]
)

X_test_cat = encoder.transform(
    X_test[categorical_columns]
)

print("Encoded training shape:", X_train_cat.shape)
print("Encoded testing shape:", X_test_cat.shape)

Encoded training shape: (42432, 210)
Encoded testing shape: (10608, 210)

In [81]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_num = scaler.fit_transform(
    X_train[numeric_columns]
)

X_test_num = scaler.transform(
    X_test[numeric_columns]
)

print("Numerical training shape:", X_train_num.shape)
print("Numerical testing shape:", X_test_num.shape)

Numerical training shape: (42432, 19)
Numerical testing shape: (10608, 19)

In [82]:

import numpy as np

X_train_prepared = np.hstack([
    X_train_num,
    X_train_cat
])

X_test_prepared = np.hstack([
    X_test_num,
    X_test_cat
])

print("Prepared training shape:", X_train_prepared.shape)
print("Prepared testing shape:", X_test_prepared.shape)

Prepared training shape: (42432, 229)
Prepared testing shape: (10608, 229)

In [83]:

import numpy as np

print("NaN values in X_train_prepared:",
      np.isnan(X_train_prepared).sum())

print("NaN values in X_test_prepared:",
      np.isnan(X_test_prepared).sum())

NaN values in X_train_prepared:

 4376
NaN values in X_test_prepared: 1099